grails-app/domain/dk/silverbullet/kihdb/model/LaboratoryReport.groovy
/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.silverbullet.kihdb.model

import dk.silverbullet.kihdb.constants.Constants
import dk.silverbullet.kihdb.enums.*

class LaboratoryReport extends AbstractObject {

    static belongsTo = [sample: SelfMonitoringSample]

    String laboratoryReportUUID
    Date createdDateTime
    String analysisText
    String resultText
    EncodingIdentifier resultEncodingIdentifier
    OperatorIdentifier resultOperatorIdentifier
    String resultUnitText
    AbnormalIdentifier resultAbnormalIdentifier
    String resultMinimumText
    String resultMaximumText
    String resultTypeOfInterval
    String nationalSampleIdentifier
    IUPACCode iupacCode
    LabProducer producerOfLabResult
    Instrument instrument

    MeasurementTransferredBy measurementTransferredBy
    MeasurementLocation measurementLocation
    MeasuringDataClassification measuringDataClassification
    String measurementDuration

    MeasurementScheduled measurementScheduled

    // How to handle those?
    String healthCareProfessionalComment
    String measuringCircumstances
    boolean deleted

    static constraints = {
        resultAbnormalIdentifier(nullable: true)
        resultEncodingIdentifier(nullable: true)
        resultOperatorIdentifier(nullable: true)
        resultMaximumText(nullable: true)
        resultMinimumText(nullable: true)
        laboratoryReportUUID(nullable: false, unique: true)
        sample(nullable: true)
        instrument(nullable: true)
        measurementLocation(nullable: true)
        measurementDuration(nullable: true)
        measurementScheduled(nullable: true)
        measurementTransferredBy(nullable: true)
        measuringDataClassification(nullable: true)
        measuringCircumstances(nullable: true)
        healthCareProfessionalComment(nullable: true)
        resultTypeOfInterval(nullable: true)
        createdBy(nullable: true)
        sample(nullable: true)
        deleted(nullable: true)
    }


    static mapping = {
        healthCareProfessionalComment type: "text"
        measuringCircumstances type: "text"
    }

    boolean isVitalSigns() {
        return Constants.VITAL_SIGN_CODES.contains(this.iupacCode.code)
    }
}

grails-app/controllers/dk/silverbullet/kihdb/model/LaboratoryReportController.groovy
/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.silverbullet.kihdb.model

import dk.silverbullet.kihdb.util.ControllerUtil
import grails.plugins.springsecurity.Secured

@Secured(PermissionName.NONE)
class LaboratoryReportController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    @Secured(PermissionName.LABORATORY_READ)
    def show(Long id) {
        def laboratoryReportInstance = LaboratoryReport.findById(id)

        ControllerUtil.setPatientSession(session, laboratoryReportInstance?.sample?.citizen)

        if (!laboratoryReportInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'laboratoryReport.label', default: 'LaboratoryReport'), id])
            redirect(action: "list")
            return
        }

        [laboratoryReportInstance: laboratoryReportInstance]
    }

}

grails-app/views/laboratoryReport/list.gsp
<%--
 Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
--%>
<%@ page import="dk.silverbullet.kihdb.model.LaboratoryReport" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'laboratoryReport.label', default: 'LaboratoryReport')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="list-laboratoryReport" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table  class="table table-hover">
				<thead>
					<tr>
                        <g:sortableColumn property="uuidIdentifier" title="${message(code: 'laboratoryReport.uuidIdentifier.label', default: 'Uuid Identifier')}" />
                        <g:sortableColumn property="createdDateTime" title="${message(code: 'laboratoryReport.createdDateTime.label', default: 'Oprettet')}" />
                        <g:sortableColumn property="nationalSampleIdentifier" title="${message(code: 'laboratoryReport.nationalSampleIdentifier.label', default: 'National Målings Id')}" />
                        <g:sortableColumn property="deleted" title="${message(code: 'laboratoryReport.deleted.label', default: 'Slette markeret')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${laboratoryReportInstanceList}" status="i" var="laboratoryReportInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${laboratoryReportInstance.id}">${fieldValue(bean: laboratoryReportInstance, field: "laboratoryReportUUID")}</g:link></td>
					
						<td><g:formatDate date="${laboratoryReportInstance.createdDateTime}" /></td>
					
						<td>${fieldValue(bean: laboratoryReportInstance, field: "nationalSampleIdentifier")}</td>

                        <td>${fieldValue(bean: laboratoryReportInstance, field: "deleted")}</td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${laboratoryReportInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/laboratoryReport/show.gsp
<%--
 Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
--%>
<%@ page import="dk.silverbullet.kihdb.model.LaboratoryReport" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'laboratoryReport.label', default: 'LaboratoryReport')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="show-laboratoryReport" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list laboratoryReport">
			
				<g:if test="${laboratoryReportInstance?.resultAbnormalIdentifier}">
				<li class="fieldcontain">
					<span id="resultAbnormalIdentifier-label" class="property-label"><g:message code="laboratoryReport.resultAbnormalIdentifier.label" default="Result Abnormal Identifier" /></span>
					
						<span class="property-value" aria-labelledby="resultAbnormalIdentifier-label"><g:message code="laboratoryReport.resultAbnormalIdentifier.value.${laboratoryReportInstance.resultAbnormalIdentifier}"/></span>
					
				</li>
				</g:if>

                <g:if test="${laboratoryReportInstance?.deleted}">
                    <li class="fieldcontain">
                        <span id="deleted-label" class="property-label"><g:message code="laboratoryReport.deleted.label" default="Slette Markeret" /></span>

                        <span class="property-value" aria-labelledby="deleted-label">${fieldValue(bean: laboratoryReportInstance, field: "deleted")}</span>

                    </li>
                </g:if>


                <g:if test="${laboratoryReportInstance?.resultEncodingIdentifier}">
				<li class="fieldcontain">
					<span id="resultEncodingIdentifier-label" class="property-label"><g:message code="laboratoryReport.resultEncodingIdentifier.label" default="Result Encoding Identifier" /></span>
					
						<span class="property-value" aria-labelledby="resultEncodingIdentifier-label"><g:message code="laboratoryReport.resultEncodingIdentifier.value.${laboratoryReportInstance.resultEncodingIdentifier}"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.resultOperatorIdentifier}">
				<li class="fieldcontain">
					<span id="resultOperatorIdentifier-label" class="property-label"><g:message code="laboratoryReport.resultOperatorIdentifier.label" default="Result Operator Identifier" /></span>
					
						<span class="property-value" aria-labelledby="resultOperatorIdentifier-label"><g:message code="laboratoryReport.resultOperatorIdentifier.value.${laboratoryReportInstance.resultOperatorIdentifier}"/></span>
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.resultMaximumText}">
				<li class="fieldcontain">
					<span id="resultMaximumText-label" class="property-label"><g:message code="laboratoryReport.resultMaximumText.label" default="Result Maximum Text" /></span>
					
						<span class="property-value" aria-labelledby="resultMaximumText-label"><g:fieldValue bean="${laboratoryReportInstance}" field="resultMaximumText"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.resultMinimumText}">
				<li class="fieldcontain">
					<span id="resultMinimumText-label" class="property-label"><g:message code="laboratoryReport.resultMinimumText.label" default="Result Minimum Text" /></span>
					
						<span class="property-value" aria-labelledby="resultMinimumText-label"><g:fieldValue bean="${laboratoryReportInstance}" field="resultMinimumText"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.sample}">
				<li class="fieldcontain">
					<span id="sample-label" class="property-label"><g:message code="laboratoryReport.sample.label" default="Sample" /></span>
					
						<span class="property-value" aria-labelledby="sample-label">${laboratoryReportInstance?.sample?.createdByText}</span>

				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.analysisText}">
				<li class="fieldcontain">
					<span id="analysisText-label" class="property-label"><g:message code="laboratoryReport.analysisText.label" default="Analysis Text" /></span>
					
						<span class="property-value" aria-labelledby="analysisText-label"><g:fieldValue bean="${laboratoryReportInstance}" field="analysisText"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.createdDateTime}">
				<li class="fieldcontain">
					<span id="createdDateTime-label" class="property-label"><g:message code="laboratoryReport.createdDateTime.label" default="Created Date Time" /></span>
					
						<span class="property-value" aria-labelledby="createdDateTime-label"><g:formatDate date="${laboratoryReportInstance?.createdDateTime}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.iupacCode}">
				<li class="fieldcontain">
					<span id="iupacCode-label" class="property-label"><g:message code="laboratoryReport.iupacCode.label" default="Iupac Code" /></span>
					
						<span class="property-value" aria-labelledby="iupacCode-label">${laboratoryReportInstance?.iupacCode?.encodeAsHTML()}</span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.nationalSampleIdentifier}">
				<li class="fieldcontain">
					<span id="nationalSampleIdentifier-label" class="property-label"><g:message code="laboratoryReport.nationalSampleIdentifier.label" default="National Sample Identifier" /></span>
					
						<span class="property-value" aria-labelledby="nationalSampleIdentifier-label"><g:fieldValue bean="${laboratoryReportInstance}" field="nationalSampleIdentifier"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.producerOfLabResult}">
				<li class="fieldcontain">
					<span id="producerOfLabResult-label" class="property-label"><g:message code="laboratoryReport.producerOfLabResult.label" default="Producer Of Lab Result" /></span>
					
						<span class="property-value" aria-labelledby="producerOfLabResult-label"><g:link controller="labProducer" action="show" id="${laboratoryReportInstance?.producerOfLabResult?.id}">${laboratoryReportInstance?.producerOfLabResult?.identifierCode}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.resultText}">
				<li class="fieldcontain">
					<span id="resultText-label" class="property-label"><g:message code="laboratoryReport.resultText.label" default="Result Text" /></span>
					
						<span class="property-value" aria-labelledby="resultText-label"><g:fieldValue bean="${laboratoryReportInstance}" field="resultText"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.resultUnitText}">
				<li class="fieldcontain">
					<span id="resultUnitText-label" class="property-label"><g:message code="laboratoryReport.resultUnitText.label" default="Result Unit Text" /></span>
					
						<span class="property-value" aria-labelledby="resultUnitText-label"><g:fieldValue bean="${laboratoryReportInstance}" field="resultUnitText"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${laboratoryReportInstance?.laboratoryReportUUID}">
				<li class="fieldcontain">
					<span id="uuidIdentifier-label" class="property-label"><g:message code="laboratoryReport.uuidIdentifier.label" default="Uuid Identifier" /></span>
					
						<span class="property-value" aria-labelledby="uuidIdentifier-label"><g:link controller="selfMonitoringSample" action="show" id="${laboratoryReportInstance?.sample?.id}"><g:fieldValue bean="${laboratoryReportInstance}" field="laboratoryReportUUID"/></g:link></span>
					
				</li>
				</g:if>
			</ol>
		</div>
	</body>
</html>